spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/gamebase}
    username: ${DB_USERNAME:admin}
    password: ${DB_PASSWORD:123qwe}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
  liquibase:
    enabled: true
    change-log: classpath:/db.changelog/changelog-master.yml
environment:
  bot:
    name: ${BOT_NAME:}
    token: ${BOT_TOKEN:}
  yandex:
    key: ${KEY:}