spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/gamebase}
    username: ${DB_USERNAME:admin}
    password: ${DB_PASSWORD:123qwe}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
  liquibase:
    enabled: true
    change-log: classpath:/db.changelog/changelog-master.yml
config:
  botName: ${BOT_NAME:}
  botToken: ${BOT_TOKEN:}
  key: ${KEY_YANDEX:}
  weatherUrl: ${URL:}